version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    environment: 
      repo_token: VF3Ta1s7mOVWqtZeYEkxyHaJ3VwemHNkw
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd ../node_mongo_tutorial && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd ../node_mongo_tutorial && npm install mocha c8 chai-http chai
      - run:
          name: Run Unit Tests
          command: cd ../node_mongo_tutorial && npm run coverage
      - run:
          name: Upload coverage to Coveralls
          command: cd ../node_mongo_tutorial && npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests
